# name of the action
name: build

# trigger on pull_request or push events
on:
  push:
  pull_request:

# pipeline to execute
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: clone
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: node
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.79.0'
        extended: true

    - name: build
      env:
        HUGO_ENV: production
      run: |
        npm install -D --save autoprefixer
        npm install -D --save postcss
        npm install -D --save postcss-cli
        hugo
